stages:
- test
- build
- deploy

include:
- template: Security/SAST.gitlab-ci.yml

default:
  tags:
  - docker

variables:
  GIT_SUBMODULE_STRATEGY: recursive

semgrep-sast:
  artifacts:
    access: developer
    reports:
      sast:
      - gl-sast-report.json
    expire_in: 1 week

test-build:
  stage: build
  image: docker:28.0.0-cli
  variables:
    BUILDX_NO_DEFAULT_ATTESTATIONS: 1
  before_script:
  - ln -f -s docker/.dockerignore .dockerignore
  script:
  - cp $Z2_CI_NODE_ENV .env.production
  - docker buildx bake --file docker/docker-bake.hcl mr
  rules:
  - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
  - when: never

build:
  stage: build
  image: docker:28.0.0-cli
  variables:
    BUILDX_NO_DEFAULT_ATTESTATIONS: 1
  before_script:
  - ln -f -s docker/.dockerignore .dockerignore
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
  - cp $Z2_CI_NODE_ENV .env.production
  - docker buildx bake --file docker/docker-bake.hcl
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: never

deploy-to-dev:
  stage: deploy
  variables:
    Z2_PARENT_TRIGGER_CI_JOB_NAME: update-version-budget-planning
    Z2_PARENT_APPLICATION_DOTENV_NAME: BUDGET_PLANNING_IMAGE_TAG
    Z2_PARENT_APPLICATION_DOTENV_VERSION: latest
  trigger:
    project: vse-deployments/dev-deployment
    strategy: depend
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    when: on_success
  - if: $CI_PIPELINE_SOURCE == "web"
    when: manual
  - when: never
