export { default as AutoComplete } from './AutoComplete'
export { default as DateInput } from './DateInput'
export { default as TextInput } from './TextInput'
export { default as Number } from './NumberInput'
export { default as Phone } from './PhoneInput'
export { default as Select } from './Select'
export { default as InputSearch } from './InputSearch'
export { Label } from './Label'
